#!/usr/bin/env python3
# ##############################################################################
# File Name        : celery_tasks.py
# File Path        : apps/school/celery_tasks.py
#
# Author           : Chalearm Saelim & Gemini
# Owner            : Chalearm Saelim
# Reviewer         : Chalearm Saelim
#
# Version          : 4.0.0
# Status           : Development
# Created Date     : 2026-07-26 08:00:00 (UTC+7)
# Modified Date    : 2026-08-05 22:30:00 (UTC+7)
#
# Description      :
#    Distributed Task Router & Broker Interface for Celery and Redis. Registers
#    asynchronous tasks for fold cross-validation training using the Native
#    Rust C++ LSTM Engine (rust_lstm_engine), visualization/export, and Post-GA
#    Out-of-Sample (OOS) Walk-Forward verification with fallback cache path
#    resolution across worker containers. Unpacks dynamic genetic parameters
#    (nodes_per_layer, learning_rate, dropout, batch_size) generated by ga_master.py.
#
# DEPENDENCY TREE & STRUCTURAL MAP:
# ───────────────────────────────────────────────────────────────────────────
# [ga_master.py] (Central Orchestrator)
#     │
#     ├── Invokes Async Tasks ──> [celery_tasks.py]
#     │                                 │
#     │                    (Redis Message Broker Queue)
#     │                                 │
#     │  ┌─────────────────────────────┼──────────────────────────────┐
#     │  ▼                             ▼                              ▼
# [tasks.run_fold_training_task] [tasks.export_and_plot_task] [tasks.run_oos_verification_task]
#     │ (Calls Rust LSTM Engine)       │                              │
#     └── Native C Extension ──> [rust_lstm_engine]                   │
#                                      └── Calls ──> [viz_worker.py]  └── Calls ──> [verify_worker.py]
#
# Responsibilities :
#    - Routes distributed task invocations through Redis broker using Celery.
#    - Unpacks dynamic chromosome hyperparameters generated by ga_master.py.
#    - Executes high-speed cross-validation training via native Rust LSTM C-extension.
#    - Handles task serialization, compression (gzip), and retry mechanics.
#    - Performs absolute path fallback resolution for missing tensor cache files.
#
# Usage :
#    Directory : apps/school/
#
# Build :
#    N/A (Interpreted Python Script)
#
# Run :
#    celery -A celery_tasks worker -n local_worker_1 --loglevel=info
#
# Dependencies :
#    Internal :
#      - rust_lstm_engine (Native Rust/C++ PyO3 extension module)
#      - visualization_worker (generate_pareto_graphs_and_exports)
#      - verify_worker (execute_oos_verification)
#
#    External :
#      - celery, redis, numpy
#
# Change History :
#    -------------------------------------------------------------------------
#    Version | Date Time (UTC+7)         | Author          | Description
#    -------------------------------------------------------------------------
#    1.0.0   | 2026-07-26 08:00:00 (UTC+7) | Chalearm Saelim | Initial version
#    1.0.1   | 2026-07-27 16:35:00 (UTC+7) | Chalearm Saelim | Registered verify task
#    3.5.0   | 2026-07-30 17:00:00 (UTC+7) | Chalearm Saelim | Added path resolution fallback & OOS task routing
#    4.0.0   | 2026-08-05 22:30:00 (UTC+7) | Chalearm Saelim | Replaced TensorFlow Keras with Rust C-extension engine;
#                                                        unpacked dynamic nodes_per_layer & chromosome genes.
#    -------------------------------------------------------------------------
#
# TODO :
#    - Add task deadline and soft-time-limit safeguards.
#
# Notes :
#    - Per regulator coding standard rules.
# ##############################################################################

import os
import sys
import json
import logging
import math
import traceback
import numpy as np
from celery import Celery

# Import Native Rust LSTM C-Extension Engine
try:
    import rust_lstm_engine
    RUST_ENGINE_AVAILABLE = True
except ImportError as imp_err:
    RUST_ENGINE_AVAILABLE = False
    print(f"⚠️ [SYSTEM WARN] Native rust_lstm_engine C-extension not compiled or found: {imp_err}")

logger = logging.getLogger(__name__)

# Ensure current script directory is on sys.path
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
if CURRENT_DIR not in sys.path:
    sys.path.insert(0, CURRENT_DIR)

# ------------------------------------------------------------------------------
# REDIS BROKER & RESULT BACKEND CONFIGURATION
# ------------------------------------------------------------------------------
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")

# 1. Instantiate Celery app object FIRST
app = Celery(
    "ga_lstm_tasks",
    broker=REDIS_URL,
    backend=REDIS_URL
)

# 2. Update worker transport and serialization parameters
app.conf.update(
    task_serializer='json',
    result_serializer='json',
    accept_content=['json'],
    result_expires=3600,
    broker_transport_options={
        'visibility_timeout': 3600,
        'socket_timeout': 30,
        'socket_connect_timeout': 30,
        'socket_keepalive': True,
    },
    redis_backend_health_check_interval=10,
    task_compression='gzip',
)
app.conf.task_routes = {
    'tasks.run_fold_training_task': {'queue': 'training_queue'},
    'tasks.export_and_plot_task': {'queue': 'export_queue'},
}


# ==============================================================================
# HELPER: CACHE PATH RESOLUTION FALLBACK
# ==============================================================================
# ##############################################################################
# Function Name : resolve_cache_file_path
# Purpose       : Validates and resolves absolute tensor cache file paths across 
#                 worker containers. Reconstructs missing fallback paths relative 
#                 to application root directory.
# ##############################################################################
def resolve_cache_file_path(payload_json: dict) -> dict:
    cache_file = payload_json.get('cache_file', '')
    run_id = payload_json.get('run_id', '')
    chrom_id = payload_json.get('chrom_id', '')

    if not cache_file or not os.path.exists(cache_file):
        app_root = os.path.dirname(os.path.abspath(__file__))
        alt_path = os.path.join(app_root, "logs", run_id, "cache", f"chrom_{chrom_id}.npz")
        
        if os.path.exists(alt_path):
            payload_json['cache_file'] = alt_path
        else:
            # Secondary fallback check relative to working directory
            pwd_path = os.path.abspath(os.path.join("logs", run_id, "cache", f"chrom_{chrom_id}.npz"))
            if os.path.exists(pwd_path):
                payload_json['cache_file'] = pwd_path

    return payload_json


# ##############################################################################
# Function Name : _safe_exp
# Purpose       : Safely computes exponential math without throwing 
#                 [Errno 34] Numerical result out of range. Clamps limits to 
#                 prevent Celery worker core dumps.
# ##############################################################################
def _safe_exp(value, clamp_max=700.0, clamp_min=-700.0):
    try:
        if np.isnan(value) or np.isinf(value):
            return 1.0
            
        safe_val = float(np.clip(value, clamp_min, clamp_max))
        return math.exp(safe_val)
    except OverflowError:
        print(f"      ⚠️ [MATH GUARD] Intercepted math.exp() overflow on value: {value}")
        return float('inf') if value > 0 else 0.0
    except Exception as e:
        print(f"      ⚠️ [MATH GUARD] Unexpected math error: {e}")
        return 1.0
 
# ##############################################################################
# Function Name : _evaluate_predictions_safely
# Purpose       : Evaluates Skill DA, RMSE, Sharpe Ratio, CAGR, Max Drawdown, 
#                 and per-asset Skill DA breakdown matrices.
# ##############################################################################
def _evaluate_predictions_safely(
    y_true: np.ndarray, 
    y_pred: np.ndarray, 
    da_ref: float = 0.5, 
    fee_bps: float = 0.0006,
    asset_names: list = None
) -> dict:
    import numpy as np

    ANNUAL_TRADING_DAYS = 365.0

    # 1. Input Sanitization
    y_true = np.nan_to_num(y_true, nan=0.0, posinf=0.15, neginf=-0.15)
    y_pred = np.nan_to_num(y_pred, nan=0.0, posinf=0.15, neginf=-0.15)

    # 2. Extract Non-Overlapping Daily 1-Step Sequences
    if len(y_true.shape) == 3:
        y_true_daily = y_true[:, 0, :]
        y_pred_daily = y_pred[:, 0, :]
    elif len(y_true.shape) == 2:
        y_true_daily = y_true
        y_pred_daily = y_pred
    else:
        y_true_daily = y_true.reshape(-1, 1)
        y_pred_daily = y_pred.reshape(-1, 1)

    # 3. Root Mean Squared Error
    mse = np.mean(np.square(y_true - y_pred))
    rmse = float(np.sqrt(mse))

    # 4. Normalized Skill Directional Accuracy (Overall)
    true_dirs = np.sign(y_true_daily)
    pred_dirs = np.sign(y_pred_daily)
    correct_dirs = np.sum(true_dirs == pred_dirs)
    total_dirs = y_true_daily.size

    da_model = float(correct_dirs / total_dirs) if total_dirs > 0 else da_ref
    skill_da = float((da_model - da_ref) / (1.0 - da_ref))

    # 5. Per-Asset Skill DA Breakdown Matrix
    asset_skills = {}
    num_assets = y_true_daily.shape[-1]
    
    for col_idx in range(num_assets):
        name = asset_names[col_idx] if (asset_names and col_idx < len(asset_names)) else f"Asset_{col_idx}"
        a_true = y_true_daily[:, col_idx]
        a_pred = y_pred_daily[:, col_idx]
        
        a_correct = np.sum(np.sign(a_true) == np.sign(a_pred))
        a_total = a_true.size
        
        a_da = float(a_correct / a_total) if a_total > 0 else da_ref
        a_skill = float((a_da - da_ref) / (1.0 - da_ref))
        
        asset_skills[name] = {
            "baseline": da_ref,
            "model": a_da,
            "skill": a_skill
        }

    # 6. Compute Return Deltas
    if y_true_daily.shape[0] > 1:
        daily_return_deltas = np.diff(y_true_daily, axis=0, prepend=y_true_daily[:1])
    else:
        daily_return_deltas = y_true_daily

    # 7. Positions & Strategy Returns
    positions = np.sign(y_pred_daily)
    position_changes = np.abs(np.diff(positions, axis=0, prepend=positions[:1]))
    trading_costs = position_changes * fee_bps

    gross_returns = positions * np.clip(daily_return_deltas, -0.15, 0.15)
    net_asset_returns = gross_returns - trading_costs
    strategy_returns = np.mean(net_asset_returns, axis=-1)

    mean_ret = float(np.mean(strategy_returns))
    std_ret = float(np.std(strategy_returns, ddof=1))

    # 8. Sharpe Ratio
    epsilon = 1e-6
    if std_ret > epsilon:
        raw_sharpe = (mean_ret / std_ret) * np.sqrt(ANNUAL_TRADING_DAYS)
        sharpe = float(np.clip(raw_sharpe, -5.0, 50.0))
    else:
        sharpe = -5.0 if mean_ret <= 0 else 0.0

    # 9. Maximum Drawdown
    cum_log_returns = np.cumsum(strategy_returns)
    safe_cum_returns = np.clip(cum_log_returns, -700.0, 700.0)
    equity_curve = np.exp(safe_cum_returns)

    running_peak = np.maximum.accumulate(equity_curve)
    drawdowns = (running_peak - equity_curve) / (running_peak + 1e-12)
    drawdowns = np.nan_to_num(drawdowns, nan=0.0, posinf=0.0, neginf=0.0)
    
    max_dd = float(np.max(drawdowns)) if len(drawdowns) > 0 else 0.0

    # 10. CAGR
    num_steps = max(1, len(strategy_returns))
    annualized_log_ret = float(np.sum(strategy_returns)) * (ANNUAL_TRADING_DAYS / num_steps)
    safe_ann_ret = float(np.clip(annualized_log_ret, -5.0, 5.0))
    cagr = float(np.exp(safe_ann_ret) - 1.0)

    return {
        "rmse": rmse,
        "raw_da": da_model,
        "skill_da": skill_da,
        "sharpe": sharpe,
        "cagr": cagr,
        "max_dd": max_dd,
        "asset_skills": asset_skills  # 🟢 POPULATES GA_MASTER BREAKDOWN
    }
# ==============================================================================
# CELERY TASK DEFINITIONS
# ==============================================================================
# ##############################################################################
# Function Name : run_fold_training_task
# Purpose       : Celery worker task that trains a candidate model on a CV fold.
#                 Dynamically extracts the chromosome payload (nodes_per_layer,
#                 learning_rate, dropout, batch_size) from ga_master.py and 
#                 delegates execution to the high-performance Native Rust LSTM 
#                 C-Extension (rust_lstm_engine).
# ##############################################################################
@app.task(bind=True, name="tasks.run_fold_training_task", max_retries=2)
def run_fold_training_task(self, payload: dict):
    import time
    start_fold_time = time.time()
    # Safely extract chromosome, Model ID, and Run ID from payload
    chromosome = payload.get('chromosome', {})
    chrom_id = payload.get('chrom_id', chromosome.get('id', 'UNKNOWN_MODEL'))
    fold_idx = payload.get('fold_idx', -1)
    run_id = payload.get('run_id', 'UNKNOWN_RUN')
    
    print("\n" + "═" * 70)
    print(f"🏋️ [FOLD WORKER START] Model: {chrom_id} | Fold: {fold_idx}")
    print("═" * 70)
    
    try:
        # ----------------------------------------------------------------------
        # 1. DYNAMIC GENETIC PARAMETER UNPACKING (FROM GA_MASTER.PY)
        # ----------------------------------------------------------------------
        nodes_per_layer = chromosome.get('nodes_per_layer', chromosome.get('nodes_list', [64]))
        if isinstance(nodes_per_layer, int):
            nodes_per_layer = [nodes_per_layer]
            
        lstm_units = int(nodes_per_layer[0]) if len(nodes_per_layer) > 0 else int(chromosome.get('lstm_units', 64))
        num_layers = len(nodes_per_layer)
        
        lr_val = float(chromosome.get('learning_rate', 0.001))
        epochs_val = int(chromosome.get('epochs', 25))  # 🟢 Dynamic GA Epochs
        batch_val = int(chromosome.get('batch_size', 32))
        dropout_val = float(chromosome.get('dropout_rate', 0.2))

        print(f"      [CHROMOSOME UNPACK] ID: {chrom_id} | Layers: {num_layers} {nodes_per_layer} | "
              f"LR: {lr_val} | Dropout: {dropout_val} | Epochs: {epochs_val} | Batch: {batch_val}")

        # ----------------------------------------------------------------------
        # 2. TENSOR EXTRACTION & FAULT-TOLERANT PATH ROUTING
        # ----------------------------------------------------------------------
        if 'cache_file' in payload:
            cache_path = payload['cache_file']
            
            # Dynamic Path Resolution: Remap absolute paths from Master to Worker
            if not os.path.exists(cache_path):
                app_root = os.path.dirname(os.path.abspath(__file__))
                filename = os.path.basename(cache_path)
                local_cache_path = os.path.join(app_root, "logs", run_id, "cache", filename)
                
                if os.path.exists(local_cache_path):
                    print(f"      [FOLD-STATE 0.5] Path Mismatch Detected. Remapped to local volume: {local_cache_path}")
                    cache_path = local_cache_path
                else:
                    raise FileNotFoundError(
                        f"Cache missing on Worker.\nMaster Path: {payload['cache_file']}\nLocal Path: {local_cache_path}"
                    )
            
            print(f"      [FOLD-STATE 1.0] Loading dataset from disk cache: {cache_path}")
            
            if str(cache_path).endswith('.npz'):
                with np.load(cache_path, allow_pickle=True) as data:
                    files = data.files
                    x_key = next((k for k in ['X_full', 'X', 'x'] if k in files), files[0])
                    y_key = next((k for k in ['y_full', 'y', 'Y'] if k in files), files[1] if len(files)>1 else files[0])
                    X_full = data[x_key]
                    y_full = data[y_key]
            else:
                import pickle
                with open(cache_path, 'rb') as f:
                    data = pickle.load(f)
                    X_full = data.get('X_full', data.get('X', data.get('x')))
                    y_full = data.get('y_full', data.get('y', data.get('Y')))
            
            train_slice = payload.get('train_slice')
            val_slice = payload.get('val_slice')
            
            def extract_slice(tensor, slice_def):
                if isinstance(slice_def, dict) and 'start' in slice_def and 'end' in slice_def:
                    return tensor[slice_def['start']:slice_def['end']]
                elif isinstance(slice_def, (list, tuple)):
                    if len(slice_def) == 2 and isinstance(slice_def[0], int) and isinstance(slice_def[1], int):
                        return tensor[slice_def[0]:slice_def[1]]
                    return tensor[slice_def]
                return tensor

            X_train = np.ascontiguousarray(extract_slice(X_full, train_slice), dtype=np.float32)
            y_train = np.ascontiguousarray(extract_slice(y_full, train_slice), dtype=np.float32)
            X_val = np.ascontiguousarray(extract_slice(X_full, val_slice), dtype=np.float32)
            y_val = np.ascontiguousarray(extract_slice(y_full, val_slice), dtype=np.float32)
            
        else:
            print(f"      [FOLD-STATE 1.0] Loading tensors directly from network payload...")
            raw_x_train = payload.get('x_train', payload.get('X_train', payload.get('train_x')))
            raw_y_train = payload.get('y_train', payload.get('Y_train', payload.get('train_y')))
            raw_x_val = payload.get('x_val', payload.get('X_val', payload.get('val_x')))
            raw_y_val = payload.get('y_val', payload.get('Y_val', payload.get('val_y')))
            
            if raw_x_train is None or raw_y_train is None:
                raise ValueError(f"Missing training tensors! Available Payload Keys: {list(payload.keys())}")
                
            X_train = np.ascontiguousarray(raw_x_train, dtype=np.float32)
            y_train = np.ascontiguousarray(raw_y_train, dtype=np.float32)
            X_val = np.ascontiguousarray(raw_x_val, dtype=np.float32)
            y_val = np.ascontiguousarray(raw_y_val, dtype=np.float32)
            
        print(f"      [FOLD-STATE 1.1] Tensors extracted safely. Training shape: {X_train.shape} | Val shape: {X_val.shape}")

        # ----------------------------------------------------------------------
        # 3. NATIVE RUST C-EXTENSION ENGINE EXECUTION
        # ----------------------------------------------------------------------
        if not RUST_ENGINE_AVAILABLE:
            raise RuntimeError("rust_lstm_engine is required but not imported on this Worker node.")

        print(f"      [FOLD-STATE 2.0] Executing Native Rust C++ LSTM Engine ({num_layers} Layers | Units: {lstm_units})...")

        raw_preds = rust_lstm_engine.train_and_predict(
            x_train_py=X_train,
            y_train_py=y_train,
            x_val_py=X_val,
            lstm_units=lstm_units,
            learning_rate=lr_val,
            epochs=epochs_val,
            _batch_size=batch_val
        )
        print(f"      [FOLD-STATE 2.1] Native Rust C++ LSTM execution complete.")

        # ----------------------------------------------------------------------
        # 4. VALIDATION INFERENCE & PREDICTION CLIPPING
        # ----------------------------------------------------------------------
        print(f"      [FOLD-STATE 3.0] Processing Rust prediction array...")
        
        # Format prediction tensor to match y_val shape
        if len(raw_preds.shape) == 3 and raw_preds.shape[1] == 1:
            raw_preds = raw_preds[:, 0, :]

        # Sanitize and clip predictions to realistic market boundaries (-10% to +10%)
        safe_preds = np.nan_to_num(raw_preds, nan=0.0, posinf=0.15, neginf=-0.15)
        safe_preds = np.clip(safe_preds, -0.15, 0.15)
        
        # Extract target asset names from payload
        target_cols = payload.get('target_cols', [])
        # ----------------------------------------------------------------------
        # 5. METRIC EVALUATION WITH ASSET NAMES
        # ----------------------------------------------------------------------
        print(f"      [FOLD-STATE 4.0] Evaluating performance metrics safely...")
        fold_metrics = _evaluate_predictions_safely(y_val, safe_preds, asset_names=target_cols)
        fold_duration = time.time() - start_fold_time
        print(f"      [FOLD-STATE 5.0] Fold {fold_idx} completed in {fold_duration:.2f}s | RMSE: {fold_metrics.get('rmse', 0.0):.4f}")

        return {
            "status": "SUCCESS",
            "chromosome_id": chrom_id,
            "fold_idx": fold_idx,
            "execution_time_sec": fold_duration,
            "metrics": fold_metrics
        }

    except Exception as err:
        error_trace = traceback.format_exc()
        
        if "MISCONF Redis" in str(err) or "ResponseError" in str(err):
            print(f"\n❌ [REDIS MISCONF ERROR] Redis background save failed on Worker node!")
            print("Fix: redis-cli config set stop-writes-on-bgsave-error no")
            return {"status": "FAILURE", "error": "Redis Background Save Error", "chromosome_id": chrom_id}
            
        print(f"\n❌ [WORKER FATAL CRASH] Model {chrom_id} | Fold {fold_idx} failed!")
        print(f"      └── Error Type: {type(err).__name__}")
        print(f"      └── Message: {err}")
        print(f"      └── Traceback:\n{error_trace}\n")
        
        return {
            "status": "FAILURE",
            "chromosome_id": chrom_id,
            "fold_idx": fold_idx,
            "execution_time_sec": fold_duration,
            "error": str(err)
        }


# ##############################################################################
# Function Name : export_and_plot_task
#
# Path          : apps/school/celery_tasks.py
# Author        : Chalearm Saelim & Gemini
#
# Purpose :
#    Celery task entry-point for post-GA out-of-sample verification and Pareto
#    frontier graph generation/artifact exports. Ingests JSON task payloads,
#    updates Celery's task state with generation-level metadata for cluster
#    telemetry reporting, and delegates plotting execution to the visualization engine.
#
# Inputs :
#    payload_json
#        Type        : dict | str
#        Description : Serialized or unpacked dictionary containing task_type,
#                      run_id, gen_idx, top_chromosomes, master_data, and val_data.
#
# Return :
#    Type        : dict
#    Description : Execution summary containing status, run_id, gen_idx, and total
#                  processed candidate model forecast count.
#
# Complexity :
#    Time  : O(1) task dispatch routing overhead.
#    Space : O(1) RAM allocation prior to worker execution.
#
# Error Cases :
#    - Catches malformed string JSON payloads and returns structured error dictionaries.
#    - Automatically triggers Celery retries (max_retries=1, countdown=5) on unexpected exceptions.
# ##############################################################################
@app.task(name="tasks.export_and_plot_task", bind=True, max_retries=1)
def export_and_plot_task(self, payload_json: dict) -> dict:
    # --------------------------------------------------------------------------
    # 1. PAYLOAD PARSING & ARGUMENT NORMALIZATION
    # --------------------------------------------------------------------------
    if isinstance(payload_json, str):
        try:
            payload_json = json.loads(payload_json)
        except Exception as parse_err:
            logger.error(f"❌ [EXPORT TASK ERROR] Failed parsing JSON payload string: {parse_err}")
            return {"status": "error", "message": f"Invalid JSON payload: {parse_err}"}

    if not isinstance(payload_json, dict):
        payload_json = {}

    task_type = payload_json.get("task_type", "GEN_PLOT")
    run_id = payload_json.get("run_id", "UNKNOWN")
    gen_idx = payload_json.get("gen_idx", 1)

    print("\n" + "⚡" * 40)
    print(f"⚡ [CELERY WORKER INGEST] Ingested export_and_plot_task")
    print(f"   ├── Task Type    : {task_type}")
    print(f"   ├── Run ID       : {run_id}")
    print(f"   ├── Generation   : {gen_idx}")
    print(f"   └── Task ID      : {self.request.id}")
    print("⚡" * 40 + "\n")

    # --------------------------------------------------------------------------
    # 2. TASK ROUTING: POST-GA OOS VERIFICATION
    # --------------------------------------------------------------------------
    if task_type == "POST_GA_OOS":
        from verify_worker import execute_oos_verification
        try:
            return execute_oos_verification(payload_json)
        except Exception as exc:
            logger.warning(f"⚠️ [OOS RETRY] Verification task failed for Run ID {run_id}: {exc}")
            raise self.retry(exc=exc, countdown=5)

    # --------------------------------------------------------------------------
    # 3. TASK STATE PROGRESS PUBLISHING (TELEMETRY BINDING)
    # --------------------------------------------------------------------------
    try:
        self.update_state(
            state="PROGRESS",
            meta={
                "run_id": run_id,
                "gen_idx": gen_idx,
                "current_candidate": "Initializing",
                "candidate_progress": "0/5",
                "display_target": f"Gen {gen_idx} Plots"
            }
        )
        payload_json["celery_task_handle"] = self
    except Exception as state_err:
        logger.warning(f"⚠️ [CELERY STATE WARN] Could not update task progress state: {state_err}")

    # --------------------------------------------------------------------------
    # 4. DEFAULT ROUTE: PARETO PLOTS & MODEL EXPORTS
    # --------------------------------------------------------------------------
    from visualization_worker import generate_pareto_graphs_and_exports
    try:
        result = generate_pareto_graphs_and_exports(payload_json)
        print(f"\n✅ [TASK SUCCESS] Pareto visualization & export completed for Run ID: {run_id} (Gen {gen_idx})")
        return result
    except Exception as exc:
        logger.warning(f"⚠️ [TASK RETRY] Visualization task failed for Run ID {run_id} (Gen {gen_idx}): {exc}")
        raise self.retry(exc=exc, countdown=5)


# ##############################################################################
# Function Name : run_oos_verification_task
# Purpose       : Offloaded Celery task executing Post-GA Out-of-Sample 
#                 Walk-Forward verification for elite chromosomes.
# ##############################################################################
@app.task(name="tasks.run_oos_verification_task", bind=True, max_retries=1)
def run_oos_verification_task(self, payload_json: dict) -> dict:
    from verify_worker import execute_oos_verification
    try:
        return execute_oos_verification(payload_json)
    except Exception as exc:
        raise self.retry(exc=exc, countdown=5)
