#!/usr/bin/env python3
"""
File Name       : serve.py
File Path       : /workspace/crypto_apps/dexbot/serve.py

Author          : deepseek-4.0-pro
Owner           : Chalearm Saelim
Version         : 1.1.0
Created Date    : 2026-06-28 14:00:00 (UTC+7)
Modified Date   : 2026-06-28 14:30:00 (UTC+7)

Description     :
  Lightweight middle HTTP server for the Dexbot dashboard (myreq3.txt
  68-70). Serves static HTML/JSON files generated by the Governance
  daemon from WEB_OUTPUT_DIR. Forwards POST action commands to Governance
  via a simple TCP connection on WEB_ACTION_PORT. Does NOT implement
  daemon logic — it is purely a static file server + action proxy.

Responsibilities:
  - Serve static HTML/JSON/CSS files from WEB_OUTPUT_DIR
  - Serve /api/* endpoints from cached JSON files
  - Forward POST /api/daemon/{name}/{action} to Governance TCP listener
  - Zero dependencies beyond Python3 stdlib

Usage :
  Directory : /workspace/crypto_apps/dexbot/
  Run       : python3 serve.py
             : python3 serve.py --port 8080 --dir web_output --action-port 8085
  Test      : curl http://localhost:8080/

Configuration :
  - WEB_OUTPUT_DIR  env var (default: web_output)
  - WEB_PORT        env var (default: 8080)
  - WEB_HOST        env var (default: 0.0.0.0)
  - WEB_ACTION_PORT env var (default: 8085) — TCP port to Governance

Dependencies :
  Internal : None
  External : Python3 stdlib only (http.server, socket, json, os, pathlib)

Updated Parts :
  [Function]
    - DexbotHandler.do_POST(): now forwards to Governance via TCP

New Parts :
  [Function]
    - forward_action(): TCP proxy to Governance action listener
"""

import http.server
import json
import os
import socket
import argparse
from pathlib import Path

# ── Configuration ──────────────────────────────────────────────

OUTPUT_DIR   = os.environ.get("WEB_OUTPUT_DIR", "web_output")
PORT         = int(os.environ.get("WEB_PORT", "8080"))
HOST         = os.environ.get("WEB_HOST", "0.0.0.0")
ACTION_PORT  = int(os.environ.get("WEB_ACTION_PORT", "8085"))
ACTION_HOST  = os.environ.get("WEB_ACTION_HOST", "127.0.0.1")


# ── Functions ───────────────────────────────────────────────────

def forward_action(name, action):
    """Forward an action command to the Governance daemon via TCP.
    Protocol: send "action name\\n", receive "OK ..." or "ERROR ..."."""
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(3)
        sock.connect((ACTION_HOST, ACTION_PORT))
        sock.sendall(f"{action} {name}\n".encode())
        response = sock.recv(256).decode().strip()
        sock.close()
        return response
    except Exception as e:
        return f"ERROR {e}"


# ── HTTP Handler ────────────────────────────────────────────────

class DexbotHandler(http.server.SimpleHTTPRequestHandler):
    """Serves static files from OUTPUT_DIR. Forwards POST actions to Governance."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=OUTPUT_DIR, **kwargs)

    def do_GET(self):
        """Handle GET — static files + API proxy."""
        if self.path.startswith("/api/"):
            self.serve_api()
            return

        if self.path == "/" or self.path.endswith("/"):
            self.path = "/index.html"
        elif not os.path.splitext(self.path)[1]:
            candidate = self.path + ".html"
            if os.path.isfile(os.path.join(OUTPUT_DIR, candidate.lstrip("/"))):
                self.path = candidate

        super().do_GET()

    def serve_api(self):
        """Serve cached JSON from output_dir/api/."""
        # /api/balance
        if self.path.startswith("/api/balance"):
            bal_file = os.path.join(OUTPUT_DIR, "api", "balance.json")
            if os.path.isfile(bal_file):
                with open(bal_file, "r") as f:
                    data = json.load(f)
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps(data, indent=2).encode())
                return
            else:
                self.send_error(404, "Balance not yet available")

        # /api/database_tables — list of table names (§87)
        if self.path.startswith("/api/database_tables"):
            fpath = os.path.join(OUTPUT_DIR, "api", "database_tables.json")
            if os.path.isfile(fpath):
                with open(fpath, "r") as f:
                    data = json.load(f)
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps(data, indent=2).encode())
                return
            else:
                self.send_error(404, "No tables available")

        # /api/database?table=X&rows=N&sort=Y — dynamic DB query (§87)
        if self.path.startswith("/api/database"):
            from urllib.parse import urlparse, parse_qs
            qs = parse_qs(urlparse(self.path).query)
            table = qs.get('table', [None])[0]
            rows_n = qs.get('rows', ['5'])[0]
            sort = qs.get('sort', ['newest'])[0]
            fpath = os.path.join(OUTPUT_DIR, "api", "database.json")
            if os.path.isfile(fpath):
                with open(fpath, "r") as f:
                    data = json.load(f)
                if table and table in data:
                    self.send_response(200)
                    self.send_header("Content-Type", "application/json")
                    self.send_header("Access-Control-Allow-Origin", "*")
                    self.end_headers()
                    self.wfile.write(json.dumps(data[table], indent=2).encode())
                    return
            self.send_error(404, "Table not found")

        api_path = self.path.replace("/api/", "").replace("/", "_") + ".json"
        file_path = os.path.join(OUTPUT_DIR, "api", api_path)

        try:
            with open(file_path, "r") as f:
                data = json.load(f)
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(json.dumps(data, indent=2).encode())
        except FileNotFoundError:
            daemon_file = os.path.join(OUTPUT_DIR, "api", "daemons.json")
            if os.path.isfile(daemon_file):
                with open(daemon_file, "r") as f:
                    data = json.load(f)
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps(data, indent=2).encode())
            else:
                self.send_error(404, "API endpoint not found")

    def do_POST(self):
        """Forward action POST to Governance via TCP or handle token CRUD."""
        # §83-84: Token editor — add token via local JSON file
        if self.path.startswith("/api/tokens/add"):
            try:
                content_len = int(self.headers.get('Content-Length', 0))
                body = self.rfile.read(content_len)
                data = json.loads(body)
                token_file = os.path.join(OUTPUT_DIR, "api", "tokens.json")
                tokens = []
                if os.path.isfile(token_file):
                    with open(token_file) as f:
                        tokens = json.load(f)
                updated = False
                for i, t in enumerate(tokens):
                    if t.get('ticker') == data.get('ticker'):
                        tokens[i] = data
                        updated = True
                        break
                if not updated:
                    tokens.append(data)
                with open(token_file, 'w') as f:
                    json.dump(tokens, f, indent=2)
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps({"status": "ok", "message": "token added"}).encode())
                return
            except Exception as e:
                self.send_error(500, str(e))
                return

        # §83-84: Token editor — delete token
        if self.path.startswith("/api/tokens/delete"):
            try:
                content_len = int(self.headers.get('Content-Length', 0))
                body = self.rfile.read(content_len)
                data = json.loads(body)
                token_file = os.path.join(OUTPUT_DIR, "api", "tokens.json")
                tokens = []
                if os.path.isfile(token_file):
                    with open(token_file) as f:
                        tokens = json.load(f)
                ticker = data.get('ticker', '')
                chain = data.get('chain_id', '')
                tokens = [t for t in tokens if not (t.get('ticker') == ticker and t.get('chain_id') == chain)]
                with open(token_file, 'w') as f:
                    json.dump(tokens, f, indent=2)
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps({"status": "ok", "message": "token deleted"}).encode())
                return
            except Exception as e:
                self.send_error(500, str(e))
                return

        # Forward daemon action to governance via TCP
        if self.path.startswith("/api/daemon/"):
            parts = self.path.replace("/api/daemon/", "").split("/")
            if len(parts) >= 2:
                name, action = parts[0], parts[1]
                result = forward_action(name, action)
                ok = result.startswith("OK")
                self.send_response(200 if ok else 500)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                resp = {"status": "ok" if ok else "error", "action": action,
                        "daemon": name, "message": result}
                self.wfile.write(json.dumps(resp).encode())
                print(f"[WEB] POST /api/daemon/{name}/{action} → {result}", flush=True)
                return

        self.send_error(400, "Invalid POST request")

    def log_message(self, format, *args):
        if "200" not in str(args[0]):
            print(f"[WEB] {args[0]}", flush=True)


# ── Main ────────────────────────────────────────────────────────

def main():
    global OUTPUT_DIR, ACTION_PORT

    parser = argparse.ArgumentParser(description="Dexbot Dashboard HTTP Server")
    parser.add_argument("--port", type=int, default=PORT, help="Listen port")
    parser.add_argument("--dir", type=str, default=OUTPUT_DIR, help="Output directory")
    parser.add_argument("--host", type=str, default=HOST, help="Bind address")
    parser.add_argument("--action-port", type=int, default=ACTION_PORT, help="Governance TCP action port")
    args = parser.parse_args()

    # Set module-level globals for handler access (before Handler reads them)
    OUTPUT_DIR = args.dir
    ACTION_PORT = args.action_port

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.makedirs(os.path.join(OUTPUT_DIR, "api"), exist_ok=True)

    server = http.server.HTTPServer((args.host, args.port), DexbotHandler)

    print(f"\n{'='*60}")
    print(f"  Dexbot Dashboard Server (middle server)")
    print(f"  HTTP on http://{args.host}:{args.port}")
    print(f"  Files  from {os.path.abspath(OUTPUT_DIR)}")
    print(f"  Actions to {ACTION_HOST}:{ACTION_PORT}")
    print(f"{'='*60}\n")

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n[WEB] Shutting down...")
        server.shutdown()


if __name__ == "__main__":
    main()
