#!/usr/bin/env python3
"""
File Name       : serve.py
File Path       : /workspace/crypto_apps/dexbot/serve.py

Author          : deepseek-4.0-pro
Owner           : Chalearm Saelim
Version         : 1.1.0
Created Date    : 2026-06-28 14:00:00 (UTC+7)
Modified Date   : 2026-06-28 14:30:00 (UTC+7)

Description     :
  Lightweight middle HTTP server for the Dexbot dashboard.
  Serves static HTML/JSON files generated by the Governance
  daemon from WEB_OUTPUT_DIR. Forwards POST action commands to Governance
  via a simple TCP connection on WEB_ACTION_PORT.
"""

import http.server
import json
import os
import socket
import argparse
import hashlib
import urllib.parse
from pathlib import Path

# ── Configuration ──────────────────────────────────────────────

OUTPUT_DIR   = os.environ.get("WEB_OUTPUT_DIR", "web_output")
PORT         = int(os.environ.get("WEB_PORT", "8080"))
HOST         = os.environ.get("WEB_HOST", "0.0.0.0")
ACTION_PORT  = int(os.environ.get("WEB_ACTION_PORT", "8085"))
ACTION_HOST  = os.environ.get("WEB_ACTION_HOST", "127.0.0.1")


# ── Functions ───────────────────────────────────────────────────

def forward_action(name, action):
    """Forward an action command to the Governance daemon via TCP.
    Protocol: send 'action name\n', receive 'OK ...' or 'ERROR ...'."""
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(3)
        sock.connect((ACTION_HOST, ACTION_PORT))
        sock.sendall(f"{action} {name}\n".encode())
        response = sock.recv(256).decode().strip()
        sock.close()
        return response
    except Exception as e:
        return f"ERROR {e}"


# ── HTTP Handler ────────────────────────────────────────────────

class DexbotHandler(http.server.SimpleHTTPRequestHandler):
    """Serves static files from OUTPUT_DIR. Forwards POST actions to Governance."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=OUTPUT_DIR, **kwargs)

    def end_headers(self):
        """Add no-cache headers to prevent stale browser cache."""
        self.send_header("Cache-Control", "no-cache, no-store, must-revalidate")
        super().end_headers()

    def _db_connect(self):
        """Lazy PostgreSQL connection for direct DB queries."""
        if not hasattr(self, '_db_conn') or self._db_conn is None or getattr(self._db_conn, 'closed', True):
            import time
            for retry in range(3):
                try:
                    import psycopg2
                    self._db_conn = psycopg2.connect(
                        host=os.environ.get('DB_HOST', 'db'),
                        port=os.environ.get('DB_PORT', '5432'),
                        user=os.environ.get('DB_USER', 'trader'),
                        password=os.environ.get('DB_PASS', 'secret'),
                        dbname=os.environ.get('DB_NAME', 'traderdb'),
                        connect_timeout=3
                    )
                    break
                except Exception:
                    if retry < 2:
                        time.sleep(1)
                    else:
                        return None
        if not hasattr(self, '_db_conn'):
            return None
        return self._db_conn

    def _db_query(self, query, params=None):
        conn = self._db_connect()
        if not conn:
            raise Exception("Cannot connect to database")
        cur = conn.cursor()
        try:
            if params:
                cur.execute(query, params)
            else:
                cur.execute(query)
            rows = cur.fetchall()
        finally:
            cur.close()
        return rows

    def _db_columns(self, table):
        conn = self._db_connect()
        if not conn:
            return []
        cur = conn.cursor()
        cur.execute(f"SELECT column_name FROM information_schema.columns WHERE table_name='{table}' ORDER BY ordinal_position")
        cols = [r[0] for r in cur.fetchall()]
        cur.close()
        return cols

    def _proxy_crud_to_balance(self, route, body):
        """Try routing a CRUD POST to the balance daemon. Returns True on success."""
        balance_port = os.environ.get("DAEMON_BALANCE_HTTP_PORT", "8085")
        balance_ip = os.environ.get("DAEMON_BALANCE_IP", "127.0.0.1")
        import urllib.request
        target = f"http://{balance_ip}:{balance_port}{route}"
        try:
            req = urllib.request.Request(target, data=body,
                headers={"Content-Type": "application/json"})
            with urllib.request.urlopen(req, timeout=5) as resp:
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(resp.read())
                return True
        except Exception as e:
            print(f"[proxy] balance daemon unreachable ({route}): {e}", flush=True)
            return False

    def do_GET(self):
        """Handle GET — static files + API proxy + URL remapping."""
        if "If-Modified-Since" in self.headers:
            del self.headers["If-Modified-Since"]
        
        if self.path.startswith("/api/"):
            self.serve_api()
            return

        # URL remapping
        if self.path == "/trading" or self.path.startswith("/trading"):
            self.path = "/portfolio.html"
        elif self.path == "/school" or self.path.startswith("/school"):
            self.path = "/training.html"
        elif self.path == "/" or self.path.endswith("/"):
            self.path = "/index.html"
        elif not os.path.splitext(self.path)[1]:
            candidate = self.path + ".html"
            if os.path.isfile(os.path.join(OUTPUT_DIR, candidate.lstrip("/"))):
                self.path = candidate

        super().do_GET()

    def serve_api(self):
        """Serve cached JSON from output_dir/api/ or proxy to balance daemon."""
    # /api/daemons -- serve cached daemon status
        if self.path == "/api/daemons":
            fpath = os.path.join(OUTPUT_DIR, "api", "daemons.json")
            if os.path.isfile(fpath):
                with open(fpath, "r") as f:
                    data = json.load(f)
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps(data).encode())
                return

        # /api/daemon/{name}/log — serve last N log lines filtered by daemon name
        if self.path.startswith("/api/daemon/") and "/log" in self.path:
            parts = self.path.strip("/").split("/")
            if len(parts) >= 4 and parts[-1] == "log":
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                name = parts[-2]
                lines = self._tail_daemon_log(name, 15)
                self.wfile.write(json.dumps({"lines": lines, "count": lines.count(chr(10))}).encode())
                return

        # /api/balance — proxy to balance daemon
        if self.path.startswith("/api/balance"):
            balance_port = os.environ.get("DAEMON_BALANCE_HTTP_PORT", "8085")
            balance_ip = os.environ.get("DAEMON_BALANCE_IP", "127.0.0.1")
            pk = ""
            if "?" in self.path:
                from urllib.parse import urlparse, parse_qs
                qs = parse_qs(urlparse(self.path).query)
                pk = qs.get("private_key", [""])[0]
            if not pk:
                pk = os.environ.get("PRIVATE_KEY", "")
            try:
                import urllib.request
                target_url = f"http://{balance_ip}:{balance_port}/api/balance"
                if pk:
                    target_url += f"?private_key={pk}"
                req = urllib.request.Request(target_url, headers={"X-Private-Key": pk} if pk else {})
                with urllib.request.urlopen(req, timeout=8) as resp:
                    data = json.loads(resp.read().decode())
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps(data).encode())
                return
            except Exception as e:
                print(f"[proxy] balance daemon unreachable ({e}), trying cached", flush=True)
                data = self._load_balance()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps(data).encode())
                return

        # /api/database_tables
        if self.path.startswith("/api/database_tables"):
            fpath = os.path.join(OUTPUT_DIR, "api", "database_tables.json")
            if os.path.isfile(fpath):
                with open(fpath, "r") as f:
                    data = json.load(f)
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps(data, indent=2).encode())
                return
            try:
                tables = self._db_query("SELECT table_name FROM information_schema.tables WHERE table_schema='public' ORDER BY table_name")
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps({"tables": [r[0] for r in tables]}, indent=2).encode())
                return
            except Exception as e:
                self.send_error(500, f"DB not available: {e}")
                return

        # /api/database dynamic queries
        if self.path.startswith("/api/database"):
            from urllib.parse import urlparse, parse_qs
            qs = parse_qs(urlparse(self.path).query)
            table = qs.get('table', [None])[0]
            rows_n = int(qs.get('rows', ['5'])[0])
            sort = qs.get('sort', ['newest'])[0]

            if not table:
                fpath = os.path.join(OUTPUT_DIR, "api", "database_tables.json")
                if os.path.isfile(fpath):
                    with open(fpath, "r") as f:
                        data = json.load(f)
                    self.send_response(200)
                    self.send_header("Content-Type", "application/json")
                    self.send_header("Access-Control-Allow-Origin", "*")
                    self.end_headers()
                    self.wfile.write(json.dumps(data, indent=2).encode())
                    return

            try:
                order = ""
                if sort in ("newest", "oldest"):
                    cols = self._db_columns(table)
                    orderCol = ""
                    for c in ["id", "created_at", "ts", "timestamp"]:
                        if c in cols:
                            orderCol = c
                            break
                    if not orderCol and len(cols) > 0:
                        orderCol = cols[0]
                    if orderCol:
                        direction = "DESC" if sort == "newest" else "ASC"
                        order = f" ORDER BY {orderCol} {direction}"
                rows = self._db_query(f"SELECT * FROM {table}{order} LIMIT {rows_n}")
                cols = self._db_columns(table)
                result = {"columns": cols, "rows": [[str(v) if v is not None else "" for v in r] for r in rows]}
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps(result, indent=2).encode())
                return
            except Exception as e:
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps({"columns": [], "rows": [], "note": f"Table not queryable: {e}"}, indent=2).encode())
                return

        api_path = self.path.replace("/api/", "").replace("/", "_") + ".json"
        file_path = os.path.join(OUTPUT_DIR, "api", api_path)

        try:
            with open(file_path, "r") as f:
                data = json.load(f)
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(json.dumps(data, indent=2).encode())
        except FileNotFoundError:
            daemon_file = os.path.join(OUTPUT_DIR, "api", "daemons.json")
            if os.path.isfile(daemon_file):
                with open(daemon_file, "r") as f:
                    data = json.load(f)
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps(data, indent=2).encode())
            else:
                self.send_error(404, "API endpoint not found")

    def verify_auth(self):
        """Check SHA256(private_key) against stored key."""
        auth = ''
        if '?auth=' in self.path:
            auth = self.path.split('?auth=')[1].split('&')[0]
        if not auth:
            auth = self.headers.get('x-auth', '')
        pk = os.environ.get('PRIVATE_KEY', '')
        if not pk:
            for p in ['config.env', '../config.env', '../../config.env']:
                try:
                    target_path = os.path.join(OUTPUT_DIR if OUTPUT_DIR else 'web_output', '..', p) if OUTPUT_DIR else p
                    with open(target_path) as fh:
                        for line in fh:
                            if line.startswith('PRIVATE_KEY='):
                                pk = line.split('=', 1)[1].strip()
                                break
                except Exception:
                    pass
        if not auth or not pk:
            return False
        expected = hashlib.sha256(pk.encode()).hexdigest()
        return auth == expected

    def write_json(self, data, code=200):
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(json.dumps(data, indent=2).encode())

    def serve_verify(self):
        path = self.path.replace('/api/verify/', '')
        clean_path = path.split('?')[0] if '?' in path else path
        method = self.command

        if clean_path not in ('ping',) and not (method == 'POST' and (clean_path.startswith('token') or clean_path.startswith('chain'))):
            if not self.verify_auth():
                self.write_json({"error": "unauthorized"}, 403)
                return

        if method == 'GET':
            if clean_path == 'balance' or clean_path.startswith('balance'):
                bal = self._load_balance()
                chain = ''
                for p in self.path.split('?')[1:] if '?' in self.path else []:
                    for kv in p.split('&'):
                        if kv.startswith('chain='):
                            chain = kv[6:]
                chain_usd = bal.get('total_usd', 0)
                if chain:
                    chain_usd = sum(a.get('usd_value', 0) for a in bal.get('assets', []) if a.get('chain_name', '') == chain)
                self.write_json({
                    "total_usd": bal.get('total_usd', 0),
                    "chain_usd": chain_usd,
                    "chain_name": chain,
                    "display_masked": "******",
                    "display_visible": "$ " + str(round(bal.get('total_usd', 0), 2)),
                    "assets_count": len(bal.get('assets', [])),
                })
                return

            if clean_path.startswith('token/'):
                ticker = clean_path.split('token/')[1].split('?')[0].upper()
                bal = self._load_balance()
                chain = ''
                for p in self.path.split('?')[1:] if '?' in self.path else []:
                    for kv in p.split('&'):
                        if kv.startswith('chain='):
                            chain = kv[6:]
                for a in bal.get('assets', []):
                    if a.get('ticker', '').upper() == ticker:
                        if chain and a.get('chain_name', '') != chain:
                            self.write_json({"ticker": ticker, "error": "token on chain " + a.get('chain_name', 'BSC') + " not " + chain, "found_on_chain": a.get('chain_name', 'BSC')})
                            return
                        self.write_json({
                            "ticker": a.get('ticker'),
                            "amount": a.get('amount', 0),
                            "usd_value": a.get('usd_value', 0),
                            "display_format": f"{a.get('ticker')} {a.get('amount', 0):.4f} (${a.get('usd_value', 0):.4f})",
                            "chain_name": a.get('chain_name', 'BSC'),
                            "address": a.get('bsc_addr', ''),
                        })
                        return
                self.write_json({"error": f"token {ticker} not found"}, 404)
                return

            if clean_path == 'tokens' or clean_path.startswith('tokens'):
                bal = self._load_balance()
                chain = ''
                for p in self.path.split('?')[1:] if '?' in self.path else []:
                    for kv in p.split('&'):
                        if kv.startswith('chain='):
                            chain = kv[6:]
                tokens = []
                for a in bal.get('assets', []):
                    if chain and a.get('chain_name', '') != chain:
                        continue
                    tokens.append({
                        "ticker": a.get('ticker'),
                        "amount": a.get('amount', 0),
                        "usd_value": a.get('usd_value', 0),
                        "display_format": f"{a.get('ticker')} {a.get('amount', 0):.4f} (${a.get('usd_value', 0):.4f})",
                        "chain_name": a.get('chain_name', 'BSC'),
                        "address": a.get('bsc_addr', ''),
                    })
                self.write_json({"tokens": tokens, "count": len(tokens)})
                return

        if method == 'POST':
            body = {}
            try:
                cl = int(self.headers.get('Content-Length', 0))
                if cl > 0:
                    body = json.loads(self.rfile.read(cl))
            except Exception:
                pass

            if clean_path == 'token/add':
                t = body.get('ticker', '').upper()
                a = body.get('address', '')
                ch = body.get('chain_name', 'BSC')
                aid = body.get('account_id', '')
                if not t or not a:
                    self.write_json({"error": "ticker and address required"}, 400)
                    return
                if aid:
                    try:
                        conn = self._db_connect()
                        if conn:
                            cur = conn.cursor()
                            cur.execute(
                                "INSERT INTO user_tokens (account_key,chain_name,ticker,address) VALUES (%s,%s,%s,%s) ON CONFLICT DO NOTHING",
                                (aid, ch, t, a))
                            conn.commit()
                            cur.close()
                    except Exception as e:
                        print(f"[TOKEN_ADD] DB save failed: {e}", flush=True)
                self.write_json({"status": "ok", "ticker": t, "address": a, "chain": ch})
                return

            if clean_path == 'token/delete':
                t = body.get('ticker', '').upper()
                ch = body.get('chain_name', 'BSC')
                aid = body.get('account_id', '')
                if not t:
                    self.write_json({"error": "ticker required"}, 400)
                    return
                if aid:
                    try:
                        conn = self._db_connect()
                        if conn:
                            cur = conn.cursor()
                            cur.execute(
                                "DELETE FROM user_tokens WHERE account_key=%s AND chain_name=%s AND ticker=%s",
                                (aid, ch, t))
                            conn.commit()
                            cur.close()
                    except Exception as e:
                        print(f"[TOKEN_DEL] DB failed: {e}", flush=True)
                self.write_json({"status": "ok", "ticker": t})
                return

            if clean_path == 'chain/add':
                n = body.get('name', '')
                i = body.get('chain_id', '') or body.get('id', '')
                aid = body.get('account_id', '')
                bu = body.get('base_url', '')
                if not n or not i:
                    self.write_json({"error": "name and id required"}, 400)
                    return
                if aid:
                    try:
                        conn = self._db_connect()
                        if conn:
                            cur = conn.cursor()
                            cur.execute(
                                "INSERT INTO user_chains (account_key,chain_name,chain_id,base_url) VALUES (%s,%s,%s,%s) ON CONFLICT DO NOTHING",
                                (aid, n, i, bu))
                            conn.commit()
                            cur.close()
                    except Exception as e:
                        print(f"[CHAIN_ADD] DB failed: {e}", flush=True)
                self.write_json({"status": "ok", "chain": n, "id": i, "base_url": bu})
                return

            if clean_path == 'chain/delete':
                n = body.get('chain_name', '')
                aid = body.get('account_id', '')
                if not n or not aid:
                    self.write_json({"error": "chain_name and account_id required"}, 400)
                    return
                try:
                    conn = self._db_connect()
                    if conn:
                        cur = conn.cursor()
                        cur.execute("DELETE FROM user_tokens WHERE account_key=%s AND chain_name=%s", (aid, n))
                        cur.execute("DELETE FROM user_chains WHERE account_key=%s AND chain_name=%s", (aid, n))
                        conn.commit()
                        cur.close()
                        self.write_json({"status": "ok", "deleted_chain": n})
                        return
                except Exception as e:
                    print(f"[CHAIN_DEL] DB failed: {e}", flush=True)
                self.write_json({"status": "error", "message": "DB unavailable"})
                return

        self.write_json({"error": "unknown verify endpoint: " + clean_path}, 404)

    def _load_balance(self):
        path = os.path.join(OUTPUT_DIR, "api", "balance.json")
        if os.path.isfile(path):
            with open(path) as f:
                data = json.load(f)
            if data.get("assets") and len(data.get("assets", [])) > 0:
                if data.get("btc_price", 0) <= 0:
                    data["btc_price"] = self._fetch_btc_price()
                return data
        return self._default_balance()

    def _fetch_btc_price(self):
        """Fetch live BTC/USD price from multiple sources with fallback."""
        try:
            import urllib.request
            url = "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd"
            req = urllib.request.Request(url, headers={"User-Agent": "Dexbot/1.0"})
            with urllib.request.urlopen(req, timeout=6) as resp:
                data = json.loads(resp.read().decode())
                price = float(data.get("bitcoin", {}).get("usd", 0))
                if price > 1000:
                    return price
        except Exception:
            pass
        try:
            import urllib.request
            url = "https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT"
            req = urllib.request.Request(url, headers={"User-Agent": "Dexbot/1.0"})
            with urllib.request.urlopen(req, timeout=6) as resp:
                data = json.loads(resp.read().decode())
                price = float(data.get("price", 0))
                if price > 1000:
                    return price
        except Exception:
            pass
        try:
            import urllib.request
            url = "https://api.bybit.com/v5/market/tickers?category=spot&symbol=BTCUSDT"
            req = urllib.request.Request(url, headers={"User-Agent": "Dexbot/1.0"})
            with urllib.request.urlopen(req, timeout=6) as resp:
                data = json.loads(resp.read().decode())
                items = data.get("result", {}).get("list", [])
                if items:
                    price = float(items[0].get("lastPrice", 0))
                    if price > 1000:
                        return price
        except Exception:
            pass
        return 60000.0

    def _default_balance(self):
        """Return token registry default assets with zero balances + live BTC price."""
        btc_price = self._fetch_btc_price()
        pk = os.environ.get('PRIVATE_KEY', '')
        masked = "no-account"
        if pk and len(pk) >= 6:
            masked = pk[:6] + '*' * (len(pk)-10) + pk[-4:]
        default_tokens = [
            {"ticker": "BNB", "amount": 0, "usd_price": 610.50, "usd_value": 0, "bsc_addr": "0x0000000000000000000000000000000000000000", "chain_id": "56", "chain_name": "BSC"},
            {"ticker": "USDT", "amount": 0, "usd_price": 1.00, "usd_value": 0, "bsc_addr": "0x55d398326f99059ff775485246999027b3197955", "chain_id": "56", "chain_name": "BSC"},
            {"ticker": "USDC", "amount": 0, "usd_price": 1.00, "usd_value": 0, "bsc_addr": "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d", "chain_id": "56", "chain_name": "BSC"},
            {"ticker": "CAKE", "amount": 0, "usd_price": 2.35, "usd_value": 0, "bsc_addr": "0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82", "chain_id": "56", "chain_name": "BSC"},
            {"ticker": "WBNB", "amount": 0, "usd_price": 610.50, "usd_value": 0, "bsc_addr": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c", "chain_id": "56", "chain_name": "BSC"},
            {"ticker": "ETH", "amount": 0, "usd_price": 3400.00, "usd_value": 0, "bsc_addr": "0x2170Ed0880ac9A755fd29B2688956BD959F933F8", "chain_id": "56", "chain_name": "BSC"},
            {"ticker": "BTT", "amount": 0, "usd_price": 0.0000003, "usd_value": 0, "bsc_addr": "0x352Cb5E19b12FC216548a2677bD0fce83BaE434B", "chain_id": "56", "chain_name": "BSC"},
            {"ticker": "SHIB", "amount": 0, "usd_price": 0.000025, "usd_value": 0, "bsc_addr": "0x2859e4544C4bB03966803b044A93563Bd2D0DD4D", "chain_id": "56", "chain_name": "BSC"},
            {"ticker": "UNI", "amount": 0, "usd_price": 3.35, "usd_value": 0, "bsc_addr": "0xBf5140A22578168FD562DCcF235E5D43A02ce9B1", "chain_id": "56", "chain_name": "BSC"},
            {"ticker": "AUTO", "amount": 0, "usd_price": 600.0, "usd_value": 0, "bsc_addr": "0xa184088a740c695E156F91f5cC086a06bb78b827", "chain_id": "56", "chain_name": "BSC"},
            {"ticker": "BSW", "amount": 0, "usd_price": 0.30, "usd_value": 0, "bsc_addr": "0x965f527d9159dce6288a2219db51fc6eef120dd1", "chain_id": "56", "chain_name": "BSC"},
        ]
        return {
            "account_name": masked,
            "account_masked": masked,
            "total_usd": 0.0,
            "total_btc": 0.0,
            "btc_price": btc_price,
            "assets": default_tokens,
            "is_paper_trade": True,
        }

    def do_POST(self):
        """Forward action POST to Governance via TCP or handle token CRUD."""
        if self.path.startswith("/api/database/delete"):
            try:
                content_len = int(self.headers.get('Content-Length', 0))
                body = self.rfile.read(content_len)
                data = json.loads(body)
                table = data.get('table', '').strip()
                rows_n = data.get('rows', 0)
                if not table:
                    self.send_error(400, "table name required")
                    return
                conn = self._db_connect()
                if not conn:
                    self.send_error(500, "DB unavailable")
                    return
                cur = conn.cursor()
                if rows_n > 0:
                    cols = self._db_columns(table)
                    orderCol = "id"
                    for c in ["id", "created_at", "ts", "timestamp"]:
                        if c in cols:
                            orderCol = c
                            break
                    cur.execute(f"DELETE FROM {table} WHERE {orderCol} IN (SELECT {orderCol} FROM {table} ORDER BY {orderCol} DESC LIMIT {rows_n})")
                else:
                    cur.execute(f"DELETE FROM {table}")
                deleted = cur.rowcount
                conn.commit()
                cur.close()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps({"status": "ok", "deleted": deleted}).encode())
                return
            except Exception as e:
                self.send_error(500, str(e))
                return

        if self.path.startswith("/api/verify/"):
            self.serve_verify()
            return

        if self.path.startswith("/api/unlock"):
            try:
                content_len = int(self.headers.get('Content-Length', 0))
                body = self.rfile.read(content_len)
                data = json.loads(body)
                pk = data.get('private_key', '').strip()
                if not pk or len(pk) < 64:
                    self.send_response(400)
                    self.send_header("Content-Type", "application/json")
                    self.send_header("Access-Control-Allow-Origin", "*")
                    self.end_headers()
                    self.wfile.write(json.dumps({"status": "error", "message": "Key too short"}).encode())
                    return
                env_path = os.path.join(OUTPUT_DIR, '..', 'config.env')
                if not os.path.isfile(env_path):
                    env_path = 'config.env'
                lines = []
                found = False
                if os.path.isfile(env_path):
                    with open(env_path) as f:
                        for line in f:
                            if line.startswith('PRIVATE_KEY='):
                                lines.append('PRIVATE_KEY=' + pk + '\n')
                                found = True
                            else:
                                lines.append(line)
                if not found:
                    lines.append('PRIVATE_KEY=' + pk + '\n')
                with open(env_path, 'w') as f:
                    f.writelines(lines)
                os.environ['PRIVATE_KEY'] = pk

                profile_id = hashlib.sha256(pk[:16].encode()).hexdigest()
                masked = hashlib.sha256(pk[:16].encode()).hexdigest()[:13]

                profile_exists = False
                chains = []
                tokens = []
                try:
                    conn = self._db_connect()
                    if conn:
                        cur = conn.cursor()
                        cur.execute("SELECT id FROM user_profiles WHERE id=%s", (profile_id,))
                        profile_exists = cur.fetchone() is not None
                        cur.close()
                except Exception:
                    pass

                if not profile_exists:
                    try:
                        conn = self._db_connect()
                        if conn:
                            cur = conn.cursor()
                            cur.execute("INSERT INTO user_profiles (id) VALUES (%s)", (profile_id,))
                            default_chains = [
                                ("BSC", "56", "https://bsc-dataseed.binance.org"),
                                ("POLYGON", "137", "https://polygon-rpc.com"),
                                ("ETHEREUM", "1", "https://eth.llamarpc.com"),
                                ("OPBNB", "204", "https://opbnb-mainnet-rpc.bnbchain.org"),
                            ]
                            for c in default_chains:
                                cur.execute(
                                    "INSERT INTO user_chains (account_key,chain_name,chain_id,base_url) VALUES (%s,%s,%s,%s) ON CONFLICT DO NOTHING",
                                    (profile_id, c[0], c[1], c[2]))
                            default_tokens = [
                                ("BSC", "BNB", "0x0000000000000000000000000000000000000000"),
                                ("BSC", "USDT", "0x55d398326f99059ff775485246999027b3197955"),
                                ("BSC", "USDC", "0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d"),
                                ("BSC", "CAKE", "0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82"),
                                ("BSC", "WBNB", "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"),
                                ("BSC", "ETH", "0x2170Ed0880ac9A755fd29B2688956BD959F933F8"),
                                ("BSC", "BTT", "0x352Cb5E19b12FC216548a2677bD0fce83BaE434B"),
                                ("BSC", "SHIB", "0x2859e4544C4bB03966803b044A93563Bd2D0DD4D"),
                                ("BSC", "UNI", "0xBf5140A22578168FD562DCcF235E5D43A02ce9B1"),
                                ("BSC", "AUTO", "0xa184088a740c695E156F91f5cC086a06bb78b827"),
                                ("BSC", "BSW", "0x965f527d9159dce6288a2219db51fc6eef120dd1"),
                                ("BSC", "BUSD", "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56"),
                                ("BSC", "BTC", "0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c"),
                                ("POLYGON", "MATIC", "0x0000000000000000000000000000000000000000"),
                                ("POLYGON", "USDT", "0xc2132d05d31c914a87c6611c10748aeb04b58e8f"),
                                ("POLYGON", "USDC", "0x3c499c542cef5e3811e1192ce70d8cc03d5c3359"),
                                ("ETHEREUM", "ETH", "0x0000000000000000000000000000000000000000"),
                                ("ETHEREUM", "USDT", "0xdac17f958d2ee523a2206206994597c13d831ec7"),
                                ("ETHEREUM", "USDC", "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"),
                                ("OPBNB", "BNB", "0x0000000000000000000000000000000000000000"),
                                ("OPBNB", "USDT", "0x9e5aac1ba1a2e6aed6b32689dfcf62a509ca96f3"),
                            ]
                            for t in default_tokens:
                                cur.execute(
                                    "INSERT INTO user_tokens (account_key,chain_name,ticker,address) VALUES (%s,%s,%s,%s) ON CONFLICT DO NOTHING",
                                    (profile_id, t[0], t[1], t[2]))
                            conn.commit()
                            cur.close()
                    except Exception as e:
                        print(f"[UNLOCK] Seed failed (non-fatal): {e}", flush=True)

                try:
                    conn = self._db_connect()
                    if conn:
                        cur = conn.cursor()
                        cur.execute("SELECT chain_name, chain_id, base_url FROM user_chains WHERE account_key=%s ORDER BY chain_name", (profile_id,))
                        for row in cur.fetchall():
                            chains.append({"name": row[0], "chain_id": row[1], "base_url": row[2]})
                        cur.execute("SELECT ticker, address, chain_name FROM user_tokens WHERE account_key=%s ORDER BY chain_name, ticker", (profile_id,))
                        for row in cur.fetchall():
                            tokens.append({"ticker": row[0], "address": row[1], "chain_name": row[2]})
                        cur.close()
                except Exception as e:
                    print(f"[UNLOCK] Load failed (non-fatal): {e}", flush=True)

                try:
                    forward_action("governance", "restart")
                except Exception:
                    pass
                addr_preview = pk[:6] + '...' + pk[-4:] if len(pk) >= 10 else ''
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps({
                    "status": "ok",
                    "address": addr_preview,
                    "profile_id": profile_id,
                    "profile_id_display": profile_id[:16] + "...",
                    "masked_key": masked[:8] + "*****",
                    "profile_exists": profile_exists,
                    "chains": chains,
                    "tokens": tokens
                }).encode())
                return
            except Exception as e:
                self.send_error(500, str(e))
                return

        if self.path.startswith("/api/verify/token/add"):
            try:
                content_len = int(self.headers.get('Content-Length', 0))
                body = self.rfile.read(content_len)
                if self._proxy_crud_to_balance("/api/token/add", body):
                    return
                data = json.loads(body)
                ticker = data.get('ticker', '').strip().upper()
                address = data.get('address', '').strip()
                chain_name = data.get('chain_name', 'BSC')
                account_id = data.get('account_id', '')
                if not ticker or not address or not account_id:
                    self.send_error(400, "ticker, address, and account_id required")
                    return
                conn = self._db_connect()
                if not conn:
                    self.send_error(500, "DB unavailable")
                    return
                cur = conn.cursor()
                cur.execute(
                    "INSERT INTO user_tokens (account_key,chain_name,ticker,address) VALUES (%s,%s,%s,%s) ON CONFLICT DO NOTHING",
                    (account_id, chain_name, ticker, address))
                conn.commit()
                cur.close()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps({"status": "ok"}).encode())
                return
            except Exception as e:
                self.send_error(500, str(e))
                return

        if self.path.startswith("/api/verify/chain/add"):
            try:
                content_len = int(self.headers.get('Content-Length', 0))
                body = self.rfile.read(content_len)
                if self._proxy_crud_to_balance("/api/chain/add", body):
                    return
                data = json.loads(body)
                name = data.get('name', '').strip()
                cid = data.get('chain_id', '').strip()
                base_url = data.get('base_url', '').strip()
                account_id = data.get('account_id', '')
                if not name or not cid or not account_id:
                    self.send_error(400, "name, chain_id, and account_id required")
                    return
                conn = self._db_connect()
                if not conn:
                    self.send_error(500, "DB unavailable")
                    return
                cur = conn.cursor()
                cur.execute(
                    "INSERT INTO user_chains (account_key,chain_name,chain_id,base_url) VALUES (%s,%s,%s,%s) ON CONFLICT DO NOTHING",
                    (account_id, name, cid, base_url))
                conn.commit()
                cur.close()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps({"status": "ok"}).encode())
                return
            except Exception as e:
                self.send_error(500, str(e))
                return

        if self.path.startswith("/api/tokens/delete"):
            try:
                content_len = int(self.headers.get('Content-Length', 0))
                body = self.rfile.read(content_len)
                if self._proxy_crud_to_balance("/api/token/delete", body):
                    return
                data = json.loads(body)
                indices = data.get('indices', [])
                chain = data.get('chain', 'BSC')
                account_id = data.get('account_id', '')
                if not account_id:
                    self.send_error(400, "account_id required")
                    return
                conn = self._db_connect()
                if not conn:
                    self.send_error(500, "DB unavailable")
                    return
                cur = conn.cursor()
                deleted = 0
                cur.execute(
                    "SELECT ticker FROM user_tokens WHERE account_key=%s AND chain_name=%s ORDER BY ticker",
                    (account_id, chain))
                rows = cur.fetchall()
                for idx in sorted(indices, reverse=True):
                    if 0 <= idx < len(rows):
                        cur.execute(
                            "DELETE FROM user_tokens WHERE account_key=%s AND chain_name=%s AND ticker=%s",
                            (account_id, chain, rows[idx][0]))
                        deleted += 1
                conn.commit()
                cur.close()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps({"status": "ok", "deleted": deleted}).encode())
                return
            except Exception as e:
                self.send_error(500, str(e))
                return

        if self.path.startswith("/api/tokens/list"):
            from urllib.parse import urlparse, parse_qs
            qs = parse_qs(urlparse(self.path).query)
            account_id = qs.get('account_id', [''])[0]
            chain = qs.get('chain', ['BSC'])[0]
            if not account_id:
                self.send_error(400, "account_id required")
                return
            try:
                conn = self._db_connect()
                if not conn:
                    self.send_error(500, "DB unavailable")
                    return
                cur = conn.cursor()
                cur.execute(
                    "SELECT ticker, address, chain_name FROM user_tokens WHERE account_key=%s AND chain_name=%s ORDER BY ticker",
                    (account_id, chain))
                tokens = [{"ticker": r[0], "address": r[1], "chain_name": r[2]} for r in cur.fetchall()]
                cur.close()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                self.wfile.write(json.dumps({"tokens": tokens, "chain": chain}).encode())
                return
            except Exception as e:
                self.send_error(500, str(e))
                return

        if self.path.startswith("/api/daemon/"):
            parts = self.path.replace("/api/daemon/", "").split("/")
            if len(parts) >= 2:
                name, action = parts[0], parts[1]
                if action == "log":
                    self._serve_daemon_log(name)
                    return
                result = forward_action(name, action)
                ok = result.startswith("OK")
                self.send_response(200 if ok else 500)
                self.send_header("Content-Type", "application/json")
                self.send_header("Access-Control-Allow-Origin", "*")
                self.end_headers()
                resp = {"status": "ok" if ok else "error", "action": action,
                        "daemon": name, "message": result}
                self.wfile.write(json.dumps(resp).encode())
                print(f"[WEB] POST /api/daemon/{name}/{action} → {result}", flush=True)
                return

        self.send_error(400, "Invalid POST request")

    def _tail_daemon_log(self, name, line_count=15):
        """Return last N lines from system.log filtered by daemon name (word boundary)."""
        log_path = os.path.join(OUTPUT_DIR, "..", "logs", "system.log")
        if not os.path.isfile(log_path):
            log_path = os.path.join("logs", "system.log")
        try:
            import re
            with open(log_path, "r") as f:
                all_lines = f.readlines()
            pattern = re.compile(r'\b' + re.escape(name) + r'\b', re.IGNORECASE)
            filtered = [l for l in all_lines if pattern.search(l)]
            if not filtered:
                filtered = [l for l in all_lines if name.lower() in l.lower()]
            return "".join(filtered[-line_count:])
        except Exception as e:
            return "Cannot read log: " + str(e)

    def _serve_daemon_log(self, name, lines=15):
        """Serve the last N lines of a daemon's log file."""
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        log_path = os.path.join(OUTPUT_DIR, "..", "logs", "system.log")
        if not os.path.isfile(log_path):
            log_path = os.path.join("logs", "system.log")
        try:
            with open(log_path, "r") as f:
                all_lines = f.readlines()
            filtered = [l for l in all_lines if name.lower() in l.lower()]
            result = filtered[-lines:]
            self.wfile.write(json.dumps({"lines": "".join(result), "count": len(result)}).encode())
        except Exception as e:
            self.wfile.write(json.dumps({"lines": "Cannot read log: " + str(e), "count": 0}).encode())

    def log_message(self, format, *args):
        if "200" not in str(args[0]):
            print(f"[WEB] {args[0]}", flush=True)


# ── Main ────────────────────────────────────────────────────────

def main():
    global OUTPUT_DIR, ACTION_PORT

    parser = argparse.ArgumentParser(description="Dexbot Dashboard HTTP Server")
    parser.add_argument("--port", type=int, default=PORT, help="Listen port")
    parser.add_argument("--dir", type=str, default=OUTPUT_DIR, help="Output directory")
    parser.add_argument("--host", type=str, default=HOST, help="Bind address")
    parser.add_argument("--action-port", type=int, default=ACTION_PORT, help="Governance TCP action port")
    args = parser.parse_args()

    OUTPUT_DIR = args.dir
    ACTION_PORT = args.action_port

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.makedirs(os.path.join(OUTPUT_DIR, "api"), exist_ok=True)

    server = http.server.HTTPServer((args.host, args.port), DexbotHandler)

    print(f"\n{'='*60}")
    print(f"  Dexbot Dashboard Server (middle server)")
    print(f"  HTTP on http://{args.host}:{args.port}")
    print(f"  Files  from {os.path.abspath(OUTPUT_DIR)}")
    print(f"  Actions to {ACTION_HOST}:{ACTION_PORT}")
    print(f"{'='*60}\n")

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n[WEB] Shutting down...")
        server.shutdown()


if __name__ == "__main__":
    main()